### ISSUE TITLE
Adatbázis feltöltése adatokkal

### ISSUE THREAD

**Issue by RostasRobert** [ibozsik94/Library#1]
A projekthez szükséges könyvek adatainak felvitele.

- [x] Szerző megadása
- [x] Cím feltöltése
- [x] Műfaj megadása
- [x] Kiadás évének megadása
- [x] ISBN szám megadása

**Comment by balipeti** [comment]
A felhasználók adatainak felvitele:
- [ ] Felhasználónév
- [ ] E-mail cím
- [ ] Jelszó
